version: "3.9"

services:
  app:
    build: .
    container_name: laravel_app
    environment:
      - DB_HOST=mysql.railway.internal
      - DB_PORT=3306
      - DB_DATABASE=railway
      - DB_USERNAME=root
      - DB_PASSWORD=sEDXrAyGvNyhyPiHaKjWihYvHOPDNtky
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - mysql

  mysql:
    image: mysql:9
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sEDXrAyGvNyhyPiHaKjWihYvHOPDNtky
      MYSQL_DATABASE: railway
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
